# Copyright (C) 2020 Huawei Technologies Co., Ltd. All rights reserved.

[base]
name = "mask_infer"
device = "rknpu"
version = "1.0.0"
description = "your description"
entry = "./yolov3_resnet18_mask_det_288x512_rknpu2.rknn"  # model file path, use relative path
type = "inference" 
virtual_type = "rknpu2" # inference engine type: rockchip now support rknpu, rknpu2(if exist)
group_type = "Inference"  # flowunit group attribution, do not change
is_input_contiguous = "false" # rk do not support memory combine, fix, do not change

# Input ports description
[input]
[input.input1]  # input port number, Format is input.input[N]
name = "data"  # input port name
type = "uint8"  # input port data type ,e.g. float or uint8
device = "rknpu"  # input buffer type: use rknpu for zero-copy, cpu also allow

# Output ports description
# [output]
# [output.output1] # output port number, Format is output.output[N]
# name = "Output"  # output port name
# type = "float"   # output port data type ,e.g. float or uint8
[output]
[output.output1]
name = "yolo/output1"
type = "float"

[output.output2]
name = "yolo/output2"
type = "float"

[output.output3]
name = "yolo/output3"
type = "float"
